server:
  host: 0.0.0.0
  port: 8080

mastertadabff:
  endpoints:
    validateJWT: /check
    logOut: /logout
    me: /proxy/me
    commands: /proxy/commands
    graphql: /proxy/graphql
    cache: /proxy/cache
    ws: /tadas-list

logger:
  name: tadas

jwt:
  keepAlive: 3600

idle:
  inactivityTime: 1800
  countdownTime: 300

fallbackLanguage: en
