server:
  host: nathanw.intdw.org
  port: 8080

mastertadabff:
  private_url: http://mastertadabff-dev09.intdw.org
  public_url: http://mastertadabff-dev09.intdw.org

tadawebapi:
  public_url: http://dev09.intdw.org:32096

checkoutAppUrl:
  public_url: nathanw.intdw.org:8082

searchAppUrl:
  public_url: nathanw.intdw.org:8081

homeAppUrl:
  public_url: nathanw.intdw.org:8080